name: pis_yedili
description: "Pis Yedili – Flutter card game"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  audioplayers: ^6.0.0
  flutter_svg: ^2.0.10+1
  flutter_gen: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/pis_yedili_basic_pack/pis_yedili_assets/deck1/
    - assets/pis_yedili_basic_pack/pis_yedili_assets/deck2/
    - assets/pis_yedili_basic_pack/pis_yedili_assets/jokers/
    - assets/pis_yedili_basic_pack/pis_yedili_assets/backs/
    - assets/icons/
    - assets/table/
    - assets/sfx/
    - assets/logo.png

# Uygulama ikonu (root seviyede olmalı; "flutter:" altında DEĞİL)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#0F1115"
  adaptive_icon_foreground: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#0F1115"
    theme_color: "#0F1115"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo.png"
